# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # # Build at 00:00 on every 3rd day-of-month.
  # schedule:
  #   - cron: "0 0 */3 * *"
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ v7 ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ v7 ]
    paths-ignore: [ '**/README.md' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cnctsun"
  cnctsun:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set TS_VER
      - name: Run version script
        run: echo "TS_VER=7.$(wget -q -O- https://www.moddb.com/mods/tiberian-sun-client/downloads/tsclient70 | grep TSClient | cut -d'.' -f2)" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a single-line script
        run: |
          sudo apt update && sudo apt install libfuse2 -y
          bash deploy.sh stable

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cnctsun-continuous-x86_64.AppImage
          path: '/home/runner/work/cnctsun_AppImage/cnctsun_AppImage/dist'

  # This workflow contains a single job called "cnctsun-wp"
  cnctsun-wp:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set TS_VER
      - name: Run version script
        run: echo "TS_VER=7.$(wget -q -O- https://www.moddb.com/mods/tiberian-sun-client/downloads/tsclient70 | grep TSClient | cut -d'.' -f2)_WP" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt update && sudo apt install libfuse2 -y
          xvfb-run --server-args="-screen 0 1024x768x24" bash deploy.sh stablewp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cnctsun-continuous-wp-x86_64.AppImage
          path: '/home/runner/work/cnctsun_AppImage/cnctsun_AppImage/dist'

  release-stable:
    needs: [cnctsun]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cnctsun-continuous-x86_64.AppImage
          path: /home/runner/work/cnctsun_AppImage/cnctsun_AppImage/cnctsun-continuous-x86_64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303
        with:
          title: cnctsun stable v7
          automatic_release_tag: stable-v7
          prerelease: false
          draft: false
          files: |
            cnctsun-continuous-x86_64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-stable-wp:
    needs: [cnctsun-wp]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cnctsun-continuous-wp-x86_64.AppImage
          path: /home/runner/work/cnctsun_AppImage/cnctsun_AppImage/cnctsun-continuous-wp-x86_64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303
        with:
          title: cnctsun stable v7 with wineprefix
          automatic_release_tag: stable-wp-v7
          prerelease: false
          draft: false
          files: |
            cnctsun-continuous-wp-x86_64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}
